### ISSUE TITLE
Privacy issue: version 0.5.0 still too 'chatty'

### ISSUE THREAD

**Issue by TP75** [nextcloud/issuetemplate#157] opened 2019-10-15 11:39 UTC
This is a helpful tool.

IMHO there is **room for improvement in protecting the privacy of a server installation** in the template report produced.

```
{
    "debug": false,
    "trusted_domains": [
        "### manually REMOVED SENSITIVE VALUE###",
        "### manually REMOVED SENSITIVE VALUE###"
    ],

    "overwrite.cli.url": "### manually REMOVED SENSITIVE VALUE###",

}
```

Please note the **text `"### manually REMOVED SENSITIVE VALUE###"` had to be edited manually** to remove sensitive values which where originally placed in the template report produced by the tool.  However, text with `"***REMOVED SENSITIVE VALUE***"` is protected sufficiently by the tool already.

The relevant output from the template report by applying version 0.5.0 on NC 16.0.5 was:

```
{
    "debug": false,
    "trusted_domains": [
        "### manually REMOVED SENSITIVE VALUE###",
        "### manually REMOVED SENSITIVE VALUE###"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.5.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "Y-m-d H:i:s",
    "log_rotate_size": 52428800,
    "loglevel": 2,
    "activity_expire_days": 190,
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "### manually REMOVED SENSITIVE VALUE###",
    "theme": "",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "updater.release.channel": "production",
    "mysql.utf8mb4": true
}
```

Hope this helps.

**Comment by nickvergessen** [comment] 2019-10-15 12:03
Duplicate of #27

**Closed by nickvergessen** 2019-10-15 12:03 UTC
